//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignmentClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAssignmentService1")]
    public interface IAssignmentService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssignmentService1/PrimeNumber", ReplyAction="http://tempuri.org/IAssignmentService1/PrimeNumberResponse")]
        string PrimeNumber([System.ServiceModel.MessageParameterAttribute(Name="primeNumber")] int primeNumber1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssignmentService1/PrimeNumber", ReplyAction="http://tempuri.org/IAssignmentService1/PrimeNumberResponse")]
        System.Threading.Tasks.Task<string> PrimeNumberAsync(int primeNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssignmentService1/Sum", ReplyAction="http://tempuri.org/IAssignmentService1/SumResponse")]
        int Sum(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssignmentService1/Sum", ReplyAction="http://tempuri.org/IAssignmentService1/SumResponse")]
        System.Threading.Tasks.Task<int> SumAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssignmentService1/ReverseString", ReplyAction="http://tempuri.org/IAssignmentService1/ReverseStringResponse")]
        string ReverseString(string initialString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssignmentService1/ReverseString", ReplyAction="http://tempuri.org/IAssignmentService1/ReverseStringResponse")]
        System.Threading.Tasks.Task<string> ReverseStringAsync(string initialString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssignmentService1/PrintHTMLTag", ReplyAction="http://tempuri.org/IAssignmentService1/PrintHTMLTagResponse")]
        string PrintHTMLTag(string tag, string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssignmentService1/PrintHTMLTag", ReplyAction="http://tempuri.org/IAssignmentService1/PrintHTMLTagResponse")]
        System.Threading.Tasks.Task<string> PrintHTMLTagAsync(string tag, string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssignmentService1/Sort5Number", ReplyAction="http://tempuri.org/IAssignmentService1/Sort5NumberResponse")]
        int[] Sort5Number(string sortType, int[] array);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssignmentService1/Sort5Number", ReplyAction="http://tempuri.org/IAssignmentService1/Sort5NumberResponse")]
        System.Threading.Tasks.Task<int[]> Sort5NumberAsync(string sortType, int[] array);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAssignmentService1Channel : AssignmentClient.ServiceReference1.IAssignmentService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AssignmentService1Client : System.ServiceModel.ClientBase<AssignmentClient.ServiceReference1.IAssignmentService1>, AssignmentClient.ServiceReference1.IAssignmentService1 {
        
        public AssignmentService1Client() {
        }
        
        public AssignmentService1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AssignmentService1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AssignmentService1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AssignmentService1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string PrimeNumber(int primeNumber1) {
            return base.Channel.PrimeNumber(primeNumber1);
        }
        
        public System.Threading.Tasks.Task<string> PrimeNumberAsync(int primeNumber) {
            return base.Channel.PrimeNumberAsync(primeNumber);
        }
        
        public int Sum(int value) {
            return base.Channel.Sum(value);
        }
        
        public System.Threading.Tasks.Task<int> SumAsync(int value) {
            return base.Channel.SumAsync(value);
        }
        
        public string ReverseString(string initialString) {
            return base.Channel.ReverseString(initialString);
        }
        
        public System.Threading.Tasks.Task<string> ReverseStringAsync(string initialString) {
            return base.Channel.ReverseStringAsync(initialString);
        }
        
        public string PrintHTMLTag(string tag, string data) {
            return base.Channel.PrintHTMLTag(tag, data);
        }
        
        public System.Threading.Tasks.Task<string> PrintHTMLTagAsync(string tag, string data) {
            return base.Channel.PrintHTMLTagAsync(tag, data);
        }
        
        public int[] Sort5Number(string sortType, int[] array) {
            return base.Channel.Sort5Number(sortType, array);
        }
        
        public System.Threading.Tasks.Task<int[]> Sort5NumberAsync(string sortType, int[] array) {
            return base.Channel.Sort5NumberAsync(sortType, array);
        }
    }
}
